name: MS Teams Deploy Card

on: [push]

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - run: date
      - run: cat /home/runner/work/_temp/_github_workflow/event.json | jq .

  build2:
    name: Build with custom name
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          timezone: Asia/Kolkata
          show-on-start: true
          show-on-exit: true
